apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::958792539882:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::958792539882:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-X282H1GEHTY2
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-03-12T16:48:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1321"
  uid: 706ee03e-54e1-467b-9e4c-d801de89e154
